#!/bin/sh -eu

X=4
Y=4
D=5
I=-1
while getopts "f:x:y:d:i:" opt; do
  case $opt in
    f) F=$OPTARG ;;
    x) X=$OPTARG ;;
    y) Y=$OPTARG ;;
    d) D=$OPTARG ;;
    i) II=$OPTARG ;;
    \?) echo "Invalid option -$OPTARG" >&2; exit 1 ;;
  esac
done
#echo "$X"
#echo "$Y"
./llvm-project/build/bin/clang -O3 -fno-unroll-loops -fno-vectorize -fno-slp-vectorize -S -emit-llvm -o extracted.ll "$F"
./llvm-project/build/bin/opt -disable-output extracted.ll -passes=cgra-extract

for folder in acc*; do
    if [ -d "$folder" ]; then
    python3 mapper/monomap.py -path "$folder"/acc_edges -x "$X" -y "$Y" -d "$D" -i "$II"
    fi
done

rm -r acc*
rm extracted.ll