#!/bin/sh -eu

X=4
Y=4
D=5
II=-1
S=0
while getopts "f:x:y:d:i:s:" opt; do
  case $opt in
    f) F=$OPTARG ;;
    x) X=$OPTARG ;;
    y) Y=$OPTARG ;;
    d) D=$OPTARG ;;
    i) II=$OPTARG ;;
    s) S=$OPTARG ;;
    \?) echo "Invalid option -$OPTARG" >&2; exit 1 ;;
  esac
done
echo "$X"
echo "$Y"

ADD_FLAGS=""
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Running on macOS"
    ADD_FLAGS+="-isysroot $(xcrun --show-sdk-path)"
else
    echo "Running on Linux/Other"
fi

./llvm-project/build/bin/clang -O3 -fno-unroll-loops -fno-vectorize -fno-slp-vectorize -S -emit-llvm $ADD_FLAGS -o extracted.ll "$F"

./llvm-project/build/bin/opt -disable-output extracted.ll -passes=cgra-extract

for folder in acc*; do
    if [ -d "$folder" ]; then
    python3 mapper/monomap.py -path "$folder"/acc_edges -x "$X" -y "$Y" -d "$D" -i "$II" -s "$S" > cgra-mono-code-"$folder"
    fi
done

#rm -r acc*
#rm extracted.ll